---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - pio-cache-pvc.yaml
  - triggers/github-webhook-secret.yaml
  - triggers/github-binding.yaml
  - triggers/event-listener.yaml
