---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - workspace-pvc.yaml
  - pio-cache-pvc.yaml
  - tasks/git-clone.yaml
  - tasks/kaniko-build-push.yaml
  - tasks/esp32-build-flash.yaml
  - pipelines/build-push.yaml
  - triggers/github-binding.yaml
  - triggers/trigger-template.yaml
  - triggers/event-listener.yaml
