apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/tektoncd/pipeline/releases/download/v0.68.0/release.yaml
  - https://github.com/tektoncd/triggers/releases/download/v0.32.0/release.yaml
  - https://github.com/tektoncd/triggers/releases/download/v0.32.0/interceptors.yaml
  - https://github.com/tektoncd/dashboard/releases/download/v0.51.0/release.yaml
