apiVersion: v1
kind: LimitRange
metadata:
  name: tekton-limits
  namespace: tekton-pipelines
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    max:
      cpu: "1"
      memory: "2Gi"
