---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-push
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
    - name: image
      type: string
    - name: dockerfile
      type: string
      default: Dockerfile
    - name: context
      type: string
      default: .
  workspaces:
    - name: shared-workspace
  results:
    - name: image-digest
      description: digest da imagem publicada
      value: $(tasks.build-push.results.IMAGE_DIGEST)
    - name: commit
      description: sha do commit clonado
      value: $(tasks.git-clone.results.commit)
  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: tekton-pipelines
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build-push
      runAfter: [git-clone]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: kaniko
          - name: namespace
            value: tekton-pipelines
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
        - name: EXTRA_ARGS
          value:
            - --skip-tls-verify
