---
# Flux monitora o registry interno em busca de novas tags do esp32-firmware.
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: esp32-firmware
  namespace: flux-system
spec:
  image: registry.wguilherme.com/esp32-firmware
  interval: 1m
