apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "header.match('X-GitHub-Event', 'push')"
      bindings:
        - ref: github-binding
      template:
        ref: build-push-trigger-template
