apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-push-trigger-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: IMAGE
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-and-push-rpi-nginx-hello-run-
      spec:
        pipelineRef:
          name: build-and-push-rpi-nginx-hello
        params:
          - name: IMAGE
            value: $(tt.params.IMAGE)
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: tekton-workspace-pvc
