apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Se usar cert-manager:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: registry.phantombyte.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 5000
  tls:
    - hosts:
        - registry.phantombyte.uk
      secretName: registry-tls
