apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-nginx-config
  namespace: registry
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;
      location / {
        proxy_pass http://registry:5000;
        auth_basic "Docker Registry";
        auth_basic_user_file /etc/nginx/auth/htpasswd;
      }
    }
