---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: default
spec:
  encryptedData:
    token: AgBjXArtUCP+a/yWL2dsNezbsMmB98ESgjwKIrDIJ4ZCNXbF391jevge+WI8I70BnEX8qry77WZMgnXMH2S3PEtwRV03AhRL8ohIJ8rQdV72fPlW888026cU+soNqVEJCtV9T2D+2IupR+/hReZn1KEEQTJUtMIR+UDMyXetTXy0CElEkpGfvp567XwfTHvxP1TSjDgK/kBMjb4+7EKmqi5JIerwreMvqXEBFZ9z91P57Ml9FL3JaQXx+Xyx1wi7cJWd/cf+xvNoltK7JMhh2kqcGv7fimUR4KvkFY+p8T55vUx1xoIpZ/6ZAFm8OC2ESy0SGLNWHHfK8RBRtbzCTsv/N7odj2FECGcaSeGyqKTprkIcgKBGwqhxrsW5YP/Ornhq+W6D/bonHyZ/ZbNoFejHXgaQYoUa8NkxLdMgJ2I/UNc7NPAyTWqBXknY5uRH3MfgJbBt3Y1anTULPWpzWP4SaBLIBUNMKTzFhjEt/M5wxq4F9cIq1NgqFUcwmEFqxGImk3K0+b77N2sLODXx1uFbEABU7xoOZP2OvlARvnagX+b7rkE6fjIPIJO5tl6L4FMcCXL9wwQuBssbl/GOKmXbYURzwY5Jt38uckoK9Ze0nCrFmBxGdBPlek92dYULp2jLttgZwmS8IU3m3RHAAwaYywcD1JBUSycdYhM+PfrzcunmdvAQ1S3qG0Qdiwis1NZMSbdXafBl+05+rJWkSuKuwH3uz3iaFgsEUAvfTlX2gWDNJTJBoF/62Zu3fjbirM1Z9Hh6jUal57ryZB5MbDpnOOdYhjm77i7pHbsFXPDHqzNNAG/ppksqkBC4F0OFAoJh9Xa3r4c8aaIdPScpIzOnD3ynBLN6y2fTbSXgru7hPAiJbTKHia74fe9b/OZKDe2OUIhE4zFoXgnA5xSv9vfzJ3J+9fa1pHs905knFFoe9CUhru5M0Q/LfI/36aosm3sPndahYWMXHNTqXnGJl3QFgyQ5qpP21oFK2Ky3RiGKJ66XgsZD8N8MB/esDJa5lngTlomIhD3Mxw==
  template:
    metadata:
      name: tunnel-token
      namespace: default
