---
- name: Preparar o nó
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: prepare
      tags: prepare

- name: Instalar K3s
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: k3s-server
      tags: k3s

- name: Instalar Cilium CNI
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: cilium
      tags: cilium

  post_tasks:
    - name: Status do cluster
      command: kubectl get nodes -o wide
      register: nodes
      changed_when: false
    - name: Exibir nodes
      debug:
        msg: "{{ nodes.stdout_lines }}"
