name: Build and Release ESP32 Firmware

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build firmware
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.build
          push: false
          load: true
          tags: esp32-builder:latest

      - name: Run build container
        run: |
          docker run --rm \
            -v $PWD:/build \
            esp32-builder:latest

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/build/bootloader.bin
            build/build/partition-table.bin
            build/build/application.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
