---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: cloudflare-tunnel-values
