cloudflare:
  tunnelName: "homelab-v8"
  # tunnelId: ""   # preencher após criar o tunnel no dashboard Cloudflare
  secretName: "tunnel-credentials"  # SealedSecret com credentials.json
  ingress:
    - hostname: "*.wguilherme.com"
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      originRequest:
        noTLSVerify: true
    - service: http_status:404

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
