---
# Tekton não tem chart Helm oficial — instalamos via GitRepository apontando
# para os releases oficiais. O Flux Kustomize Controller aplica a partir de
# ./config (que contém kustomization.yaml em cada repo Tekton).
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-pipelines
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/tektoncd/pipeline
  ref:
    tag: v0.65.0
  ignore: |
    /*
    !/config/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-triggers
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/tektoncd/triggers
  ref:
    tag: v0.30.0
  ignore: |
    /*
    !/config/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-dashboard
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/tektoncd/dashboard
  ref:
    tag: v0.49.0
  ignore: |
    /*
    !/config/
