apiVersion: apps/v1
kind: Deployment
metadata:
  name: phantom-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phantom-blog
  template:
    metadata:
      labels:
        app: phantom-blog
    spec:
      containers:
        - name: phantom-blog
          image: wguilherme/phantom-blog
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128mi"
---
apiVersion: v1
kind: Service
metadata:
  name: phantom-blog-svc
spec:
  selector:
    app: phantom-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
