---
- name: Verify K3s is running
  become: true
  command: systemctl is-active k3s
  register: k3s_status
  changed_when: false
  failed_when: k3s_status.stdout != "active"

- name: Verify kubectl works
  command: kubectl get nodes
  register: kubectl_result
  changed_when: false

- name: Display cluster nodes
  debug:
    msg: "{{ kubectl_result.stdout_lines }}"

- name: Verify K3s version
  command: k3s --version
  register: k3s_version_output
  changed_when: false

- name: Display K3s version
  debug:
    msg: "K3s version: {{ k3s_version_output.stdout }}"

- name: Check cluster resources
  command: kubectl get all -A
  register: cluster_resources
  changed_when: false

- name: Display cluster resources summary
  debug:
    msg: "Cluster has {{ cluster_resources.stdout_lines | length }} resources running"