---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go-hello
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/go-hello/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
