---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: go-hello
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-hello
  filterTags:
    pattern: '^\d{14}-[a-f0-9]{8}$'
  policy:
    alphabetical:
      order: asc
