---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: go-hello
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Image Automation
        email: flux@wguilherme.com
      messageTemplate: "chore: update go-hello image"
    push:
      branch: main
  update:
    strategy: Setters
    path: ./apps/go-hello/deploy
