---
# TriggerBinding — extrai campos do payload do webhook GitHub e os
# mapeia para parâmetros do TriggerTemplate.
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: gitbranch
      value: $(body.ref)
    - name: reponame
      value: $(body.repository.name)
