---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-webhook-secret
  namespace: tekton-pipelines
spec:
  encryptedData:
    secret: AgCXORGKBMbLKg8Rqkw9Bff7wbAY1QP1cKxoKFQVIrCIbz2EAuDrl9VXMChG4M/fKd89Mpn83A9mOPVnKKrnJcOahyr7HDt+SVZrNDMPwF1xuwYx47MBrPkyeEff3NGDUGhiGk5Em+ZPj/PzR+OGyEfzDrYwVoCr2Q1pH8uDxkK8bRgzh1xdNFIOpUaFTpiepIypQViQeVuWb82QWwBtyFS4qd1Olid1Z2nKqwHizuRc4Ldl7kbJgq20iFHgRwLOyRffkeHQXyosRCxvwlg9F+/Um3F5tqCPe0u1ewu6t8BCrlg/DzPzmTZEc6D9BXru0yQQcTDWlzSBqHn20hh09iT722xq80m9+yd9UjZirM4EsYB1yFtf8xOmSuMoNeZjnpLFAYDRSdgHqm+g9tn+SOF5K3VDucnbAj0IQKJN87xkQyVyb79LtWjt6BoiZ5uxj030BlMWoyygfspOlB0RJvRnTLMj5FT9kWlLO5yauqwq6e3+CqIRIhC7lHaqYvh5SjNmwv77QVzT304rN4ldzqepThwTYYGo130SWjaoXzjSp3fQbPtEgK/Drr2h5F8WOMYW03e+tX7G8RZjqSkTId6o+IdKrCHC/+a68Ry7Zx0VUIYq9ToeycKEMoj1b3T3rZepcQk7svdb8tD/1c/b1O/uPzOQjdeA6+49PUBw/4FeCZkPUi34TKzK92YVDVTpgAcUfDHITm0+kBqQDnLOar4tNFBlgT+Cpfh0mVAugs5cESgwW9O/Zodq
  template:
    metadata:
      name: github-webhook-secret
      namespace: tekton-pipelines
