apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install/
  - config/pipeline.yaml
  - config/rbac.yaml
  - config/event-listener.yaml
  - config/limitrange.yaml
patches:
  - path: config/namespace.yaml
