---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAL7zuy5B+KoIKiRdJ4+UExt7JppGYbqtijj2pAbrwZvuOYjkHYcDWMWhsJrjENckXFBhFmSYtNGVYarZuq67nGyMRP6uzTrNKdfkRTa3HfwL0KIBExGX8R5fM2STfC23yrvxF/84toIeGewh+4Wc5fbz9VuwutBiabB61FQ3iHNKSYNykyxv8ZolKdDVOzLlvcMk/YZ0/c855aXRZIod/T9Lro4IM5gg3k+IfcWuSBp5tj/FuJaQ6F+aucFX6GYbGhEI5jTVGaMa3ygX5FuZfnTWy81dWznA73vBTnt3ES/qJ8gLm3zkIe5Yz9EAi/B0x17Uye1gbpFRk3skAORpmHg7BQlqiGTWn1Kc62/jffu5+TIYhy2s3ln7kPUib6c7BCVbM1Dm1WXDAy/kvsxjFFdN7y5BjGGdX++zqe9OWg3KCsNYOTSVcMV/x/xOD9XqCYwcxF4cMDgrtlWXG42fyvNdhYMaph19P/z+yFg77PR+eEFHdUGRGCWU0Mgac6QdZeEYnKnH/BBGanohPfEPU3BSbDRLcgi2boj18ry6Jej2LsIlSL6UPRHCrqUclNObYrQiQIvcW8aqzi843pyARXgYgzpaDEGwT5AMxRhgSh2f00K/B3Ujmn2HiwbxYshwjMQwSJ/5GwziM0LF0fjv6GKz2Pu+mdXkCzGnnWU4kxz0v9le7DPWx+iUEt/npLGoQ5K+doxwZCaOoH4TTK0LTqga0JksK9V8q8Xm3llMdufdg2HqR2nprD0a/QdKoJxEAqW2V6mHqFesQwt1uRNXGGpUi9k8pOJ8dgwAtw6/82ZrB6j9hTXIOU6t42FHBLamFPm8J7fb0v01Xjc2iIY1Sp2QtTExuToExB7Vb6ALrNi9R5uLfELSKQ4pv7S5YfHJx2WdWCtliaG3bCXEH000Sr1eAJQL+eY0m2kw==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
