---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAKDwUMcC0aTyKqNwuumv3PLO6ZkCi1VxfsdOcM7qbXjTnKjYaAY+x6GhftTChUXYhBYJ+xMLYCedKtvMT2w4vccOSntXh0r7iiPb1zrEyLYWc6X0s8geA2F0LJgAaw3P1SAP5Kjc156aHoB7BJmEHTmAU4f0nbB3YKMS2wLAY9TvTv4vsgkqXE71rDGU/t8C1m0acO6MN8V+SxmYNaz0Um752tyzw5HN0vXQqfEVFC3MbsYk1dAuHEe8wmEeobjMCOxqgEI902h2dyz45JlTKshRIqUe0LqPkuMaV/BeFS9QRDMRyERi4MwSISKFOEItSh0dIZ2KyGtxhGXTQ7wgGBXrFCLuq7QAs9ANuXRIna1jfRXWPQBwcpKU4tkeS6tSi8lw+1ISkFLdjKh/Yz15120M2b4KPxHQosGajZ1McwKdTahr0+PTwXbf5TM+g1tPrhmhnsqMgv4xnJUU/BMJpwHKXt/k3dMVYs2zlkKQoKoSCD9NIpvI9kjWqUa0SKGlGk4HUWHQwKUgOtUnvkVetAKV4le0sghaqgx6JryJ8BXaAs72RUE5w/YGFMegwkiJ7e7O5IYNI+G2O6P74elOeEU45ndettENCmsgDrTkz8TQShQIdC0+ZoM3fTBNLTZWpKfVLUOkM9zhk7l+IbCgalESWxd8JIR8L6h5ee7tvyftql2AWiyty/oah+PWxjRNTJ9MhMv+mHLmR2H2c2Tvpo0KThV+2VxyXOUt5NL/XpnNq5VTNgvTT5XTEvI/SsfhtTK64up4o59DJMcwbjZ90ODD7KC9Ocwt1vDNP3Bi8nH7S/0bdztHmpkoG4KiwceDqjthgf1Q39nP25Tf/pzuU1ORojdTsdyx29h7Yl01E4Zx/VdwIEb2vL2mdn1HutuwNWKBLY5sDaigBbM5IuJ1inEupZ+zHUxMprhQ==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
