# yaml-language-server: $schema=false
---
cloudflare:
  tunnelName: "rpi"
  tunnelId: "9cbe39d5-4db7-42be-99e4-05496ae59c46"
  secretName: "tunnel-credentials"
  ingress:
    # Roteia tudo para o Nginx Ingress Controller
    - hostname: "*.wguilherme.com"
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      originRequest:
        noTLSVerify: true
    - service: http_status:404

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
