# ESPHome Secrets Configuration Template
# Copy this file to secrets.yaml and fill in your actual credentials

# WiFi Configuration
wifi_ssid: "Your_WiFi_SSID"
wifi_password: "your_wifi_password"

# Fallback Access Point
ap_password: "fallback_password"

# ESPHome API Password
api_password: "your_api_password"

# OTA Update Password
ota_password: "your_ota_password"

# Optional: MQTT Configuration (if using MQTT instead of API)
# mqtt_broker: "192.168.1.100"
# mqtt_username: "esphome"
# mqtt_password: "mqtt_password"

# Optional: Home Assistant Configuration
# ha_url: "http://192.168.1.100:8123"
# ha_token: "your_long_lived_access_token"