[env:usb]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
upload_speed = 115200
board_build.partitions = no_ota.csv
build_flags =
    -D LED_BUILTIN=2

[env:ota]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = esp32-base.local
upload_flags =
    --auth=ota123
    --port=3232
build_flags =
    -D LED_BUILTIN=2
