version: "3.8"

services:
  hello-python:
    build:
      context: .
    container_name: chello-python
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - .:/app
