---
all:
  children:
    k3s_cluster:
      hosts:
        rpi-k3s:
          ansible_host: 198.19.249.58 # Ajuste para o IP do seu Raspberry Pi
          ansible_user: pi # Usuário padrão do Raspberry Pi OS
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3

      vars:
        # K3s cluster configuration
        k3s_version: "v1.28.5+k3s1"
        k3s_install_options:
          - "--disable=traefik"
          - "--write-kubeconfig-mode=644"
          - "--tls-san={{ ansible_host }}"
          - "--node-ip={{ ansible_host }}"

        # Single node configuration
        k3s_node_role: "server"
        k3s_single_node: true

        # Raspberry Pi specific
        k3s_disable_swap: true
        k3s_enable_cgroups: true

        # Kubeconfig
        k3s_fetch_kubeconfig: true
        k3s_local_kubeconfig_path: "{{ playbook_dir }}/../kubeconfig"

        # Ansible connection settings
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_become: true
        ansible_become_method: sudo
