---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cert-manager-config/
  - ../nginx-ingress/
  - ../cloudflare-tunnel/
  - ../zot/
  - ../tekton/
  - ../nfd/
  - ../smarter-device-manager/
  - ../postgresql-coder/
  - ../coder/
