version: "3.8"

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --host 0.0.0.0
