---
- name: Install Nginx Ingress Controller only
  hosts: k3s_cluster
  gather_facts: true
  
  roles:
    - role: nginx-ingress
      tags: nginx
  
  post_tasks:
    - name: Verify Nginx Ingress deployment
      command: kubectl get pods -n ingress-nginx
      register: nginx_pods
      changed_when: false
      
    - name: Show Nginx Ingress status
      debug:
        msg: "{{ nginx_pods.stdout_lines }}"