---
- name: Setup K3s single-node cluster
  hosts: k3s_cluster
  gather_facts: true
  any_errors_fatal: true
  
  roles:
    - role: k3s
      tags: k3s
  
  post_tasks:
    - name: Display K3s status
      command: kubectl get nodes
      register: nodes_status
      changed_when: false
      
    - name: Show cluster status
      debug:
        msg: "{{ nodes_status.stdout_lines }}"