---
apiVersion: v1
kind: Secret
metadata:
  name: my-public-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/seu-usuario/seu-repositorio-publico.git

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minha-aplicacao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seu-usuario/seu-repositorio-publico.git
    targetRevision: HEAD
    path: caminho/para/seus/manifestos
  destination:
    server: https://kubernetes.default.svc
    namespace: meu-namespace-de-destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
