---
apiVersion: v1
kind: Secret
metadata:
  name: platform
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/wguilherme/platform.git
  username: seu-usuario-github
  password: seu-token-github

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wguilherme/platform.git
    targetRevision: HEAD
    path: rpi/deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: rpi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
