apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: monitoring
spec:
  global:
    clusterName: gke-k8s-prd
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key

  features:
    logCollection:
      enabled: true
      containerCollectAll: true
