---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager
  namespace: smarter-device-manager
data:
  conf.yaml: |
    - devicematch: ^ttyUSB[0-9]*$
      nummaxdevices: 4
    - devicematch: ^ttyACM[0-9]*$
      nummaxdevices: 4
