---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smarter-device-manager
  namespace: smarter-device-manager
  labels:
    app: smarter-device-manager
spec:
  selector:
    matchLabels:
      app: smarter-device-manager
  template:
    metadata:
      labels:
        app: smarter-device-manager
    spec:
      hostPID: true
      serviceAccountName: smarter-device-manager
      priorityClassName: system-node-critical
      containers:
        - name: smarter-device-manager
          image: ghcr.io/smarter-project/smarter-device-manager:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: config
              mountPath: /root/config
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: config
          configMap:
            name: smarter-device-manager
