title: Welcome to my blog :D
email: hello@phantombyte.uk
description: >-
  This is my personal blog, where I write about my studies, projects, and experiments.
baseurl: ""
url: "https://blog.phantombyte.uk"
github_username: wguilherme

goat_counter: phantom

permalink: /:slug.html

remote_theme: wguilherme/jekyll-minimal-synthwave

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
