---
- name: Check if Helm is installed
  command: which helm
  register: helm_check
  changed_when: false
  failed_when: false

- name: Install Helm
  when: helm_check.rc != 0
  block:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Install Helm
      become: true
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Remove Helm installation script
      file:
        path: /tmp/get_helm.sh
        state: absent

- name: Add Helm repository
  command: helm repo add {{ nginx_ingress_helm_repo_name }} {{ nginx_ingress_helm_repo_url }}
  register: helm_repo_add
  changed_when: "'has been added' in helm_repo_add.stdout"
  failed_when: helm_repo_add.rc != 0 and "already exists" not in helm_repo_add.stderr

- name: Update Helm repository cache
  command: helm repo update
  changed_when: false