---
- name: Wait for Nginx Ingress Controller deployment
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ nginx_ingress_helm_release_name }}-controller"
    namespace: "{{ nginx_ingress_namespace }}"
    wait: true
    wait_sleep: 10
    wait_timeout: "{{ nginx_ingress_wait_timeout }}"
    wait_condition:
      type: Progressing
      status: "True"
      reason: NewReplicaSetAvailable

- name: Get Nginx Ingress Controller pods
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ nginx_ingress_namespace }}"
    label_selectors:
      - app.kubernetes.io/name=ingress-nginx
  register: nginx_pods

- name: Display Nginx Ingress Controller status
  debug:
    msg: 
      - "Nginx Ingress Controller deployed successfully!"
      - "Pods running: {{ nginx_pods.resources | length }}"
      - "Service type: {{ nginx_ingress_service_type }}"

- name: Get Nginx Ingress service information
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: "{{ nginx_ingress_helm_release_name }}-controller"
    namespace: "{{ nginx_ingress_namespace }}"
  register: nginx_service

- name: Display service endpoints
  debug:
    msg: "{{ nginx_service.resources[0].status | default({}) }}"
  when: nginx_service.resources | length > 0