---
- name: Wait for Nginx Ingress Controller deployment
  shell: |
    kubectl wait --for=condition=available --timeout={{ nginx_ingress_wait_timeout }}s \
      deployment/{{ nginx_ingress_helm_release_name }}-controller \
      -n {{ nginx_ingress_namespace }}
  register: wait_result
  changed_when: false

- name: Get Nginx Ingress Controller pods
  command: kubectl get pods -n {{ nginx_ingress_namespace }} -l app.kubernetes.io/name=ingress-nginx --no-headers
  register: nginx_pods
  changed_when: false

- name: Count pods
  set_fact:
    pod_count: "{{ nginx_pods.stdout_lines | length }}"

- name: Display Nginx Ingress Controller status
  debug:
    msg: 
      - "Nginx Ingress Controller deployed successfully!"
      - "Pods running: {{ pod_count }}"
      - "Service type: {{ nginx_ingress_service_type }}"

- name: Get Nginx Ingress service information
  command: kubectl get svc {{ nginx_ingress_helm_release_name }}-controller -n {{ nginx_ingress_namespace }} -o wide
  register: nginx_service
  changed_when: false

- name: Display service information
  debug:
    msg: "{{ nginx_service.stdout_lines }}"