---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: go-hello-trigger
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      metadata:
        generateName: go-hello-ci-
        namespace: tekton-pipelines
      spec:
        timeout: 30m
        podTemplate:
          nodeSelector:
            kubernetes.io/hostname: raspberry
        taskRef:
          name: go-hello-ci
        params:
          - name: revision
            value: $(tt.params.gitrevision)
        workspaces:
          - name: source
            emptyDir: {}
