name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List directory contents
        run: |
          ls -la
          ls -la rpi/deployments/nginx-hello/

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: wguilherme
        run: |
          cd rpi/deployments/nginx-hello/
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile not found!"
            exit 1
          fi
          docker build -t $DOCKER_USERNAME/go-hello-argocd:${{ github.sha }} .
          docker push $DOCKER_USERNAME/go-hello-argocd:${{ github.sha }}

      - name: Update deployment file
        run: |
          sed -i 's|image: .*go-hello-argocd:.*|image: wguilherme/go-hello-argocd:${{ github.sha }}|' rpi/deployments/nginx-hello/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add rpi/deployments/nginx-hello/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
