name: Build and Push Image to Container Registry
on:
  push:
    branches: [main]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes in specific folder
        id: check
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt
          if grep -q "^rpi/projects/phantom-blog/" changes.txt; then
            echo "Changes detected in rpi/projects/phantom-blog/"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in rpi/projects/phantom-blog/ detected, skipping build and deploy steps"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  # Only run if changes in rpi/projects/phantom-blog
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.should_run == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./rpi/projects/phantom-blog
          file: ./rpi/projects/phantom-blog/Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: wguilherme/phantom-blog:latest, wguilherme/phantom-blog:${{ github.sha }}

      - name: Debug Git status
        run: |
          git status
          git remote -v
          git branch

      - name: Update deployment file
        run: |
          sed -i 's|image: .*phantom-blog:.*|image: wguilherme/phantom-blog:${{ github.sha }}|' rpi/projects/phantom-blog/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add rpi/deployments/nginx-hello/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
        env:
          PAT: ${{ secrets.PAT }}
