name: Build and Push Image to Container Registry
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./rpi/projects/phantom-blog
          file: ./rpi/projects/phantom-blog/Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: wguilherme/phantom-blog:latest, wguilherme/phantom-blog:${{ github.sha }}
